name: "Security Scan - Dependency Review"

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v2
        with:
          base-ref: ^refs/heads/master$
