
name: Validate Survey Completion
on:
  issues:
    types:
      - closed
      - edited

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub event
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"
